/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MyGovernor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyGovernor__factory>
getContractFactory(name: 'MyTimelock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyTimelock__factory>
getContractFactory(name: 'ProtocolToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ProtocolToken__factory>
getContractFactory(name: 'SimpleVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimpleVault__factory>

  getContractAt(name: 'MyGovernor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyGovernor>
getContractAt(name: 'MyTimelock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyTimelock>
getContractAt(name: 'ProtocolToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ProtocolToken>
getContractAt(name: 'SimpleVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimpleVault>

  deployContract(name: 'MyGovernor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyGovernor>
deployContract(name: 'MyTimelock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyTimelock>
deployContract(name: 'ProtocolToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ProtocolToken>
deployContract(name: 'SimpleVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleVault>

  deployContract(name: 'MyGovernor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyGovernor>
deployContract(name: 'MyTimelock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyTimelock>
deployContract(name: 'ProtocolToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ProtocolToken>
deployContract(name: 'SimpleVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleVault>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  